### ISSUE TITLE
Add histogram for sample

### ISSUE THREAD

**Issue by BrainStone** [jzillmann/jmh-visualizer#7]
When the type is sample data for an histogram is collected. Showing that data would be cool!

**Comment by jzillmann** [comment]
Hey @BrainStone , do you have any project or example suite where i could check the result and how it looks ?

**Comment by BrainStone** [comment]
AuraDevelopmentTeam/BungeeChat2@benchmark

**Comment by jzillmann** [comment]
Hey @BrainStone just deployed version 0.5.1 which shows the 'rawDataHistogram' instead of the 'rawData' when the benchmark mode is 'sample'.

Your posted example in the other ticket had around 1000 datapoints per iteration. Rendering all iterations for all forks turned out very slow, so i cut the histograms to max 2 iterations of max 2 forks.

Let me know how that works for you!
